//PASIEN
export const PASIEN_GET_DATA_SUCCESS = 'PASIEN_GET_DATA_SUCCESS'
export const PASIEN_DETAIL = 'PASIEN_DETAIL'

//UPDATE_PAGE
export const UPDATE_PAGE = 'UPDATE_PAGE'

//ANTRIAN
export const ANTRIAN_GET_DATA_SUCCESS = 'ANTRIAN_GET_DATA_SUCCESS'
export const ANTRIAN_DETAIL = 'ANTRIAN_DETAIL'
export const RINCIAN_DETAIL = 'RINCIAN_DETAIL'
export const ANTRIAN_MODAL_SHOW = 'ANTRIAN_MODAL_SHOW'
export const ANTRIAN_MODAL_HIDDEN = 'ANTRIAN_MODAL_HIDDEN'

//TARIF
export const TARIF_DETAIL = 'TARIF_DETAIL'
export const TARIF_GET_DATA_SUCCESS = 'TARIF_GET_DATA_SUCCESS'
export const TARIF_MODAL_SHOW = 'TARIF_MODAL_SHOW'
export const TARIF_MODAL_HIDDEN = 'TARIF_MODAL_HIDDEN'

//TEKNISI
export const TEKNISI_DETAIL = 'TEKNISI_DETAIL'
export const TEKNISI_GET_DATA_SUCCESS = 'TEKNISI_GET_DATA_SUCCESS'
export const TEKNISI_MODAL_SHOW = 'TEKNISI_MODAL_SHOW'
export const TEKNISI_MODAL_HIDDEN = 'TEKNISI_MODAL_HIDDEN'

//PELAYANAN
export const PELAYANAN_GET_DATA_SUCCESS = 'PELAYANAN_GET_DATA_SUCCESS'

//BOOKING
export const BOOKING_GET_DATA_SUCCESS = 'BOOKING_GET_DATA_SUCCESS'
